### ISSUE TITLE
app crash on Settings-> General

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#198]
Tested against v0.8.1..
on an LG Nexus 5X running Android 8 (where the bug is reproducible).
on Android 4.4.4, and Android 7 (where the bug doesn't occur).

To reproduce..
1) Navigate to Settings-> General. The app crashes before the activity gets a chance to display (force close).

2) After triggering the bug reopen the app and check the log - it indicates the calculator pref was erroneously set to "missing", causing the fallback calculator to load instead. The fallback lacks support for the moon functionality - this causes a separate crash (NPE) on subsequent attempts to open the moon dialog.

**Comment by forrestguice** [comment]
```
16:24:13 E AndroidRuntime : FATAL EXCEPTION: main
16:24:13 E AndroidRuntime : Process: com.forrestguice.suntimeswidget, PID: 13618
16:24:13 E AndroidRuntime : java.security.InvalidParameterException: Calculator value for missing not found.
16:24:13 E AndroidRuntime : at com.forrestguice.suntimeswidget.calculator.SuntimesCalculatorDescriptor.valueOf(SuntimesCalculatorDescriptor.java:123)
16:24:13 E AndroidRuntime : at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.onSharedPreferenceChanged(SuntimesSettingsActivity.java:276)
16:24:13 E AndroidRuntime : at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:560)
16:24:13 E AndroidRuntime : at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:443)
16:24:13 E AndroidRuntime : at android.preference.Preference.tryCommit(Preference.java:1589)
16:24:13 E AndroidRuntime : at android.preference.Preference.persistString(Preference.java:1625)
16:24:13 E AndroidRuntime : at android.preference.ListPreference.setValue(ListPreference.java:148)
16:24:13 E AndroidRuntime : at com.forrestguice.suntimeswidget.settings.ListPreference.setValue(ListPreference.java:67)
16:24:13 E AndroidRuntime : at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.loadPref_calculator(SuntimesSettingsActivity.java:1012)
16:24:13 E AndroidRuntime : at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.initPref_general(SuntimesSettingsActivity.java:451)
16:24:13 E AndroidRuntime : at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.access$200(SuntimesSettingsActivity.java:60)
16:24:13 E AndroidRuntime : at com.forrestguice.suntimeswidget.SuntimesSettingsActivity$GeneralPrefsFragment.onCreate(SuntimesSettingsActivity.java:385)
16:24:13 E AndroidRuntime : at android.app.Fragment.performCreate(Fragment.java:2593)
16:24:13 E AndroidRuntime : at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
16:24:13 E AndroidRuntime : at android.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1319)
16:24:13 E AndroidRuntime : at android.app.FragmentTransition.calculateFragments(FragmentTransition.java:1203)
16:24:13 E AndroidRuntime : at android.app.FragmentTransition.startTransitions(FragmentTransition.java:101)
16:24:13 E AndroidRuntime : at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
16:24:13 E AndroidRuntime : at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
16:24:13 E AndroidRuntime : at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
16:24:13 E AndroidRuntime : at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
16:24:13 E AndroidRuntime : at android.os.Handler.handleCallback(Handler.java:789)
16:24:13 E AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:98)
16:24:13 E AndroidRuntime : at android.os.Looper.loop(Looper.java:164)
16:24:13 E AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:6541)
16:24:13 E AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
16:24:13 E AndroidRuntime : at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
16:24:13 E AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

The "missing" value is supplied because the `key` provided in `onSharedPreferenceChanged` can't be found. The API docs indicate `onSharedPreferenceChanged` may be called when a preference is removed - that might be what is happening here (although the reason the problem doesn't occur on earlier versions is unknown).

**Comment by forrestguice** [comment]
The key can't be found because the `onSharedPreferenceChanged` code is now called when the pref is initialized to its default (as defined in xml). That is the apparent difference between api26 and earlier versions. In this case the key isn't going to exist. The resulting crash actually masks another problem, which is that the default value `any` (previously ignored) is now resolved (to sunrisesunsetlib) and saved to prefs before the fragment is shown. After managing the exception, the fix is actually pretty simple - fix the actual xml defaults (and maybe remove support for `any`).
