### ISSUE TITLE
crash when opening general settings

### ISSUE THREAD

**Issue by verdulo** [forrestguice/SuntimesWidget#315]
When language is set to Esperanto and you open settings => general, the application crashes. The problem occurs since version, which added displaying shadow length.
```
Errors from logcat:
04-10 12:46:05.489  2859  2859 E AndroidRuntime: Process: com.forrestguice.suntimeswidget, PID: 2859

04-10 12:46:05.489  2859  2859 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesSettingsActivity}: java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2583)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5765)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: Caused by: java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.util.Formatter.badArgumentType(Formatter.java:1489)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.util.Formatter.transformFromInteger(Formatter.java:1689)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.util.Formatter.transform(Formatter.java:1461)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.util.Formatter.doFormat(Formatter.java:1081)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:1042)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:1011)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at java.lang.String.format(String.java:1554)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at android.content.res.Resources.getQuantityString(Resources.java:509)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at com.forrestguice.suntimeswidget.SuntimesUtils.formatAsHeight(SuntimesUtils.java:961)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.formatObserverHeightSummary(SuntimesSettingsActivity.java:1474)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.loadPref_observerHeight(SuntimesSettingsActivity.java:1470)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.initPref_general(SuntimesSettingsActivity.java:652)

04-10 12:46:05.489  2859  2859 E AndroidRuntime: 	at com.forrestguice.suntimeswidget.SuntimesSettingsActivity.access$200(SuntimesSettingsActivity.java:84)`
```

**Comment by forrestguice** [comment]
ugh. This appears to be an oversight on my part. I changed some formatting symbols across all strings but neglected to change the Esperanto file.

I'll tag v0.11.3 beginning of next week including this fix.
