### ISSUE TITLE
Intent resolution bugs

### ISSUE THREAD

**Issue by AssassinRain** [forrestguice/SuntimesWidget#353]
Hello, we find several bugs in the code of 14 activities in version 0.11.3
Because all these activities are exported ones, i.e., be exposed to outside, they may receive unfriendly commands and then lead to app crash. 
Please help to confirm whether these crashes are bugs or just because of the misexposure of activities.
We believe that fixing these bugs will further improve the robustness of this app.
## 1.com.forrestguice.suntimeswidget.SuntimesActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.forrestguice.suntimeswidget.LocationConfigView.bundleData(LocationConfigView.java:743)
	at com.forrestguice.suntimeswidget.LocationConfigView.bundleData(LocationConfigView.java:735)
	at com.forrestguice.suntimeswidget.LocationConfigView.loadSettings(LocationConfigView.java:682)
	at com.forrestguice.suntimeswidget.LocationConfigDialog.onCreateDialog(LocationConfigDialog.java:276)
	at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:310)
	at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1166)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at com.forrestguice.suntimeswidget.SuntimesActivity.onStart(SuntimesActivity.java:348)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
	at android.app.Activity.performStart(Activity.java:7200)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)*

## 2.com.forrestguice.suntimeswidget.alarmclock.ui.AlarmDismissActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to resume activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.alarmclock.ui.AlarmDismissActivity}: java.lang.NumberFormatException: For input string: ""A""
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NumberFormatException: For input string: ""A""
	at java.lang.Long.parseLong(Long.java:590)
	at java.lang.Long.parseLong(Long.java:632)
	at android.content.ContentUris.parseId(ContentUris.java:86)
	at com.forrestguice.suntimeswidget.alarmclock.ui.AlarmDismissActivity.onResume(AlarmDismissActivity.java:223)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
	at android.app.Activity.performResume(Activity.java:7361)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)*
## 3.com.forrestguice.suntimeswidget.MoonWidget0ConfigActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.MoonWidget0ConfigActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 4.com.forrestguice.suntimeswidget.SuntimesConfigActivity0_2x1
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0_2x1}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 5.com.forrestguice.suntimeswidget.SuntimesConfigActivity0
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 6.com.forrestguice.suntimeswidget.MoonWidget0ConfigActivity_3x1
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.MoonWidget0ConfigActivity_3x1}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 7.com.forrestguice.suntimeswidget.MoonWidget0ConfigActivity_2x1
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.MoonWidget0ConfigActivity_2x1}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 8.com.forrestguice.suntimeswidget.SuntimesConfigActivity1
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity1}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 9.com.forrestguice.suntimeswidget.ClockWidget0ConfigActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.ClockWidget0ConfigActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 10.com.forrestguice.suntimeswidget.SuntimesConfigActivity2_3x1
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity2_3x1}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 11.com.forrestguice.suntimeswidget.SuntimesConfigActivity2_3x2
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity2_3x2}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 12.com.forrestguice.suntimeswidget.ClockWidget0ConfigActivity_3x1
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.ClockWidget0ConfigActivity_3x1}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 13.com.forrestguice.suntimeswidget.SuntimesConfigActivity2
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity2}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*
## 14.com.forrestguice.suntimeswidget.SolsticeWidget0ConfigActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SolsticeWidget0ConfigActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.LocationConfigView.cancelGetFix()' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:191)
	at android.app.Activity.performDestroy(Activity.java:7479)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)*

**Comment by forrestguice** [comment]
Well... you've flagged the main activity, the activity that dismisses sounding alarms, and each of the widget configuration activities. They are all null pointer exceptions. I will look more closely here but frankly I don't really understand what you are doing or why. Are you a user of the app and have observed these bugs in practice? or is this some kind of free security audit (for whom? is your activity associated with utopia.io in any way?). I hope not to sound rude, but if you could be clear about these things that would be great.

**Comment by AssassinRain** [comment]
Thanks for your kindly reply.
We are a group of researchers focusing on detecting the potential bugs of Android apps.
Our tool have detected that there are some potential bugs in your released apps.
So we write to you to ensure that if these potential bugs could harm the function of your apps?

**Comment by forrestguice** [comment]
I can confirm that these are bugs. These activities must be exposed for the app to work properly, but there were cases where invalid input was not handled (leading to crash). 

1. is caused by assuming that Intent data contains an absolute URI (the app supports "geo://"), but then crashes when supplied with a relative URI (unsupported).

2. is caused by assuming that Intent data contains a valid ID, but then crashes when supplied with something other than long.

3. (through 14; they are the same) is caused by finishing the activity early (due to invalid params), but then attempting to clean-up an uninitialized reference in onDestroy.

> to ensure that if these potential bugs could harm the function of your apps?
I don't think these bugs have been observed during actual use, since they require intentionally using the app in ways it wasn't designed, but in any case the correct behavior is a graceful exit.

**Comment by forrestguice** [comment]
Thanks for sharing your findings - if you discover more then please report. The "intent resolution" was pretty much untested before (but now I'm thinking I need to write a few automated tests). I agree identifying and fixing these issues will improve the robustness of this app.

**Comment by AssassinRain** [comment]
I'm sorry I forgot to reply to your comment, and we were so thankful for you fixed the exception.
