### ISSUE TITLE
Window Leak in SuntimesActivity after rotation the screen

### ISSUE THREAD

**Issue by seg-ha** [forrestguice/SuntimesWidget#407]
E/WindowManager( 6699): 
E/WindowManager( 6699): android.view.WindowLeaked: Activity com.forrestguice.suntimeswidget.SuntimesActivity has leaked window android.support.v7.app.AppCompatDelegateImplV9$ListMenuDecorView{52baab8c V.E..... ......I. 0,0-0,0} that was originally added here
E/WindowManager( 6699): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager( 6699): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager( 6699): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager( 6699): 	at android.support.v7.app.AppCompatDelegateImplV9.openPanel(AppCompatDelegateImplV9.java:1198)
E/WindowManager( 6699): 	at android.support.v7.app.AppCompatDelegateImplV9.onKeyUpPanel(AppCompatDelegateImplV9.java:1517)
E/WindowManager( 6699): 	at android.support.v7.app.AppCompatDelegateImplV9.onKeyUp(AppCompatDelegateImplV9.java:964)
E/WindowManager( 6699): 	at android.support.v7.app.AppCompatDelegateImplV9.dispatchKeyEvent(AppCompatDelegateImplV9.java:958)
E/WindowManager( 6699): 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:318)
E/WindowManager( 6699): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1962)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3845)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3819)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3551)
E/WindowManager( 6699): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3711)
E/WindowManager( 6699): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2010)
E/WindowManager( 6699): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1704)
E/WindowManager( 6699): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1695)
E/WindowManager( 6699): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1987)
E/WindowManager( 6699): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
E/WindowManager( 6699): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/WindowManager( 6699): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/WindowManager( 6699): 	at android.os.Looper.loop(Looper.java:123)
E/WindowManager( 6699): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager( 6699): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager( 6699): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager( 6699): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager( 6699): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager( 6699): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by forrestguice** [comment]
Thanks for reporting. I'll take a look at this. There are a variety of reasons the window may be leaked, so if you have any additional info, it may be helpful.

What were you doing in the app when you rotated the screen? e.g. is it associated with one of the dialogs or menus being open vs happening every time.

**Comment by seg-ha** [comment]
Steps to reproduce:
1. press menu button in main screen
2. rotate the screen

I observe this in Android emulator which contains a physical menu button.

![image](https://user-images.githubusercontent.com/64624424/80854357-209fff80-8c6a-11ea-8530-28a6e2eea5d3.png)

**Comment by forrestguice** [comment]
It doesn't happen on my older test device (api 19), but I'm able to reproduce it using emulator (api 22+). I'm not sure why its happening or how to fix it..

I can't seems to trace the exception back to any Suntimes code, and nothing really unusual about the code that shows the menu. This seems to be a bug in the support library (currently set to `25.4.0`, but also occurs w/ earlier version `25.3.1`).

This looks like the same thing.. 
https://stackoverflow.com/questions/39523722/android-widget-popupwindowpopupdecorview-leak-when-rotate-device-with-menu-open

So does 
https://stackoverflow.com/questions/43454400/open-optionsmenu-of-activity-leaks-window-on-device-rotation,
and https://stackoverflow.com/questions/59620576/android-toolbar-popup-menu-windowleaked-when-orientation-change,
but no solutions given.
