### ISSUE TITLE
app crash when changing locales from SuntimesAlarms

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#482]
To reproduce:
1) Open SuntimesAlarms.
2) Navigate `Overflow` -> `Settings` -> `Language Settings`; 
3) Change the language to any other value.
4) Press `Back` twice to navigate back to SuntimesAlarms.

I see the app crash at this point, with an exception in the logcat. The app seems to work normally after reopening it.

```
02-10 09:12:00.902 30946-30946/com.forrestguice.suntimeswidget D/localeForLanguageTag: tag: en :: locale: en
02-10 09:12:00.902 30946-30946/com.forrestguice.suntimeswidget I/loadLocale: en
02-10 09:12:00.912 30946-30946/com.forrestguice.suntimeswidget D/DEBUG: initDefaults
02-10 09:12:00.942 30946-30946/com.forrestguice.suntimeswidget D/setSelectedRowID: -1
02-10 09:12:00.942 30946-30946/com.forrestguice.suntimeswidget D/DEBUG: reloadAdapter
02-10 09:12:01.012 30946-30946/com.forrestguice.suntimeswidget E/TextView: Saved cursor position 4/4 out of range for (restored) text 
02-10 09:12:01.022 30946-30946/com.forrestguice.suntimeswidget E/TextView: Saved cursor position 4/4 out of range for (restored) text 
02-10 09:12:01.022 30946-30946/com.forrestguice.suntimeswidget E/TextView: Saved cursor position 4/4 out of range for (restored) text 
02-10 09:12:01.172 30946-30946/com.forrestguice.suntimeswidget D/DEBUG: onListLoaded: 3
02-10 09:12:01.182 30946-30946/com.forrestguice.suntimeswidget D/AndroidRuntime: Shutting down VM
02-10 09:12:01.182 30946-30946/com.forrestguice.suntimeswidget W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41b52d58)
02-10 09:12:01.192 30946-30946/com.forrestguice.suntimeswidget E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.forrestguice.suntimeswidget, PID: 30946
    java.lang.IndexOutOfBoundsException: setSpan (2 ... 2) ends beyond length 0
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1016)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:592)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:588)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.widget.EditText.setSelection(EditText.java:87)
        at android.widget.NumberPicker$SetSelectionCommand.run(NumberPicker.java:2181)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5057)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
        at dalvik.system.NativeStart.main(Native Method)
02-10 09:12:01.192 1071-1372/? W/ActivityManager:   Force finishing activity com.forrestguice.suntimeswidget/.alarmclock.ui.AlarmClockActivityLauncher
```

This is kind of a strange exception.. I can't tell where its coming from.

I can't seem to reproduce it with emulator (api28), but it happens reliably on my older device (api19). Kind of a mystery, since there isn't a NumberPicker anywhere in the view hierarchy..

**Comment by forrestguice** [comment]
Tested this again recently; the exception is only thrown when the alarm list is empty.

**Comment by forrestguice** [comment]
This looks like the same thing, and includes a suggested fix:

> _TimePicker and NumberPicker causes 'force close' when rotating screen_
> [https://issuetracker.google.com/issues/36936584](https://issuetracker.google.com/issues/36936584)
