### ISSUE TITLE
crash when using 'sun position' shortcut

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#567]
Since `v0.14.0` the 'sun position' shortcut causes a crash. 

From the launcher or home screen, long press `Suntimes -> Sun Position`

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.TimeZone com.forrestguice.suntimeswidget.calculator.SuntimesRiseSetDataset.timezone()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.TimeZone com.forrestguice.suntimeswidget.calculator.SuntimesRiseSetDataset.timezone()' on a null object reference
        at com.forrestguice.suntimeswidget.LightMapDialog.setData(LightMapDialog.java:132)
        at com.forrestguice.suntimeswidget.SuntimesActivity.showLightMapDialog(SuntimesActivity.java:2102)
        at com.forrestguice.suntimeswidget.SuntimesActivity.handleIntent(SuntimesActivity.java:279)
        at com.forrestguice.suntimeswidget.SuntimesActivity.onCreate(SuntimesActivity.java:258)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```
Tested with `v0.14.1` (crashes), and with `v0.13.19` (works correctly).

**Comment by aWildHuman** [comment]
I experience this same issue when launching the Action via the widget.
