### ISSUE TITLE
sun data source crash

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#743]
**Describe the bug**
Changing sun data source to (sunrisesunsetlibl OR ca.rmen.sunrisesunset ) make app crash

**To Reproduce**
1. Go to settings -> general -> sun data source
2. Chnge it to  (sunrisesunsetlibl OR ca.rmen.sunrisesunset)
3. Go back to the main screen

**Version Info:**
 - App Version: 0.15.8
 - Android Version: 13

**Additional context**
FATAL EXCEPTION: main
Process: com.forrestguice.suntimeswidget, PID: 19185
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Calendar.clone()' on a null object reference
	at com.forrestguice.suntimeswidget.calculator.SuntimesData.midpoint(SuntimesData.java:387)
	at com.forrestguice.suntimeswidget.calculator.SuntimesEquinoxSolsticeData.calculate(SuntimesEquinoxSolsticeData.java:220)
	at com.forrestguice.suntimeswidget.equinox.EquinoxDataAdapter.createData(EquinoxDataAdapter.java:104)
	at com.forrestguice.suntimeswidget.equinox.EquinoxDataAdapter.initData(EquinoxDataAdapter.java:80)
	at com.forrestguice.suntimeswidget.equinox.EquinoxCardView.isImplemented(EquinoxCardView.java:202)
	at com.forrestguice.suntimeswidget.SuntimesActivity.updateViews(SuntimesActivity.java:1886)
	at com.forrestguice.suntimeswidget.SuntimesActivity.onStart(SuntimesActivity.java:464)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1566)
	at android.app.Activity.performStart(Activity.java:8570)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3934)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by forrestguice** [comment]
Thanks. I think I accidentally introduced this with addition of cross-quarter days. 
It should be fixed in `v0.15.9`.
