### ISSUE TITLE
Crash when tapping on date

### ISSUE THREAD

**Issue by bege10** [forrestguice/SuntimesWidget#751]
**Describe the bug**
When I tap on the date (to change it) the app crashes

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Version Info:**
 - App Version: [ 0.15.8]
 - Android Version: [ 12]
 - Device Model: [Fairphone 3]

**Additional context**
Add any other information about the problem here.
```
FATAL EXCEPTION: main
Process: com.forrestguice.suntimeswidget, PID: 23443
java.lang.RuntimeException: Unable to resume activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.TimeDateDialog.setTimezone(java.util.TimeZone)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4824)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4857)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:146)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.TimeDateDialog.setTimezone(java.util.TimeZone)' on a null object reference
	at com.forrestguice.suntimeswidget.SuntimesActivity.onResume(SuntimesActivity.java:518)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1492)
	at android.app.Activity.performResume(Activity.java:8197)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4814)
```

**Comment by forrestguice** [comment]
Thanks. I discovered a typo at that line.
It will be fixed in the next patch.
