### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#792]
**Describe the bug**
some times clicking on "solstice / equinox" make app crash

> FATAL`` EXCEPTION: main
Process: com.forrestguice.suntimeswidget, PID: 29335
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forrestguice.suntimeswidget.equinox.EquinoxDataAdapter.setThemeOverride(com.forrestguice.suntimeswidget.themes.SuntimesTheme)' on a null object reference
	at com.forrestguice.suntimeswidget.equinox.EquinoxCardDialog.themeViews(EquinoxCardDialog.java:291)
	at com.forrestguice.suntimeswidget.equinox.EquinoxCardDialog.themeViews(EquinoxCardDialog.java:317)
	at com.forrestguice.suntimeswidget.SuntimesActivity.showEquinoxDialog(SuntimesActivity.java:2430)
	at com.forrestguice.suntimeswidget.SuntimesActivity$11.onClick(SuntimesActivity.java:1220)
	at com.forrestguice.suntimeswidget.views.ViewUtils$ThrottledClickListener.onClick(ViewUtils.java:168)
	at com.forrestguice.suntimeswidget.equinox.EquinoxCardView$1.onClick(EquinoxCardView.java:241)
	at com.forrestguice.suntimeswidget.equinox.EquinoxDataAdapter$1.onClick(EquinoxDataAdapter.java:165)
	at android.view.View.performClick(View.java:7799)
	at android.view.View.performClickInternal(View.java:7776)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31144)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8727)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by forrestguice** [comment]
Thanks for the report.
I'm able to reproduce this when "overriding" the app theme with one of the widget themes.

As a workaround, I think you can avoid the crash by changing appearance to either 'default' or 'contrast' (and avoiding the button that allow selecting the others).
